### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by keniz** [ROCmSoftwarePlatform/rocALUTION#112]
Hi, I try to install rocALUTION on our system using:
HIP version: 2.8.19361-cbe6b65e
HCC clang version 10.0.0
Got following error message:

[  1%] Building HIPCC object src/CMakeFiles/rocalution_hip.dir/base/hip/rocalution_hip_generated_hip_matrix_hyb.cpp.o
In file included from /public/home/keniz/smflow/rocALUTION-develop/src/base/hip/hip_matrix_hyb.cpp:40:
/public/home/keniz/smflow/rocALUTION-develop/src/base/hip/hip_sparse.hpp:141:38: error: unknown type name 'rocsparse_direction'; did you mean 'rocsparse_action'?
                                     rocsparse_direction       dir,
                                     ^~~~~~~~~~~~~~~~~~~
                                     rocsparse_action
/opt/rocm/include/rocsparse-types.h:181:3: note: 'rocsparse_action' declared here
} rocsparse_action;
  ^
In file included from /public/home/keniz/smflow/rocALUTION-develop/src/base/hip/hip_matrix_hyb.cpp:40:
/public/home/keniz/smflow/rocALUTION-develop/src/base/hip/hip_sparse.hpp:282:40: error: unknown type name 'rocsparse_direction'; did you mean 'rocsparse_action'?
                                       rocsparse_direction       dir,
                                       ^~~~~~~~~~~~~~~~~~~
                                       rocsparse_action
/opt/rocm/include/rocsparse-types.h:181:3: note: 'rocsparse_action' declared here
} rocsparse_action;
  ^
2 errors generated.
In file included from /public/home/keniz/smflow/rocALUTION-develop/src/base/hip/hip_matrix_hyb.cpp:40:
/public/home/keniz/smflow/rocALUTION-develop/src/base/hip/hip_sparse.hpp:141:38: error: unknown type name 'rocsparse_direction'; did you mean 'rocsparse_action'?
                                     rocsparse_direction       dir,
                                     ^~~~~~~~~~~~~~~~~~~
                                     rocsparse_action
/opt/rocm/include/rocsparse-types.h:181:3: note: 'rocsparse_action' declared here
} rocsparse_action;
  ^
In file included from /public/home/keniz/smflow/rocALUTION-develop/src/base/hip/hip_matrix_hyb.cpp:40:
/public/home/keniz/smflow/rocALUTION-develop/src/base/hip/hip_sparse.hpp:282:40: error: unknown type name 'rocsparse_direction'; did you mean 'rocsparse_action'?
                                       rocsparse_direction       dir,
                                       ^~~~~~~~~~~~~~~~~~~
                                       rocsparse_action
/opt/rocm/include/rocsparse-types.h:181:3: note: 'rocsparse_action' declared here
} rocsparse_action;
  ^
2 errors generated.
CMake Error at rocalution_hip_generated_hip_matrix_hyb.cpp.o.cmake:174 (message):
  Error generating file
  /public/home/keniz/smflow/rocALUTION-develop/build/src/CMakeFiles/rocalution_hip.dir/base/hip/./rocalution_hip_generated_hip_matrix_hyb.cpp.o

make[2]: *** [src/CMakeFiles/rocalution_hip.dir/build.make:156: src/CMakeFiles/rocalution_hip.dir/base/hip/rocalution_hip_generated_hip_matrix_hyb.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:124: src/CMakeFiles/rocalution_hip.dir/all] Error 2

**Comment by ntrost57** [comment]
You need to install latest [rocSPARSE](https://github.com/ROCmSoftwarePlatform/rocSPARSE) (e.g. clone and build it from github).
