### ISSUE TITLE
ghost part of global matrix 

### ISSUE THREAD

**Issue by keniz** [ROCmSoftwarePlatform/rocALUTION#113]
Hi,
I am trying to initialize a global matrix for multiple GPUs computation with:
void SetDataPtrCSR(int **local_row_offset, int **local_col, ValueType **local_val, int **ghost_row_offset, int **ghost_col, ValueType **ghost_val, std::string name, int local_nnz, int ghost_nnz).

At this movement, I have a matrix in distributed CSR format (which includes the ghost information, as used in PETSC). The equation indexing is pretty simple:
node0: 1->N
node1: N+1->2N
node2: 2N+1->3N
......

I am confusing with the ghost part of the inputs.

I wonder  where can I get more information about it.

Thank you very much.

**Comment by keniz** [comment]
nothing there

**Comment by ntrost57** [comment]
If you click the link from above, it will redirect you to the global matrix/vector, parallel manager and file I/O for distributed matrices. You will have to fill the interior and ghost / halo part on each node, including the communication pattern as described in the documentation.

**Comment by keniz** [comment]
Thanks, I found the common.hpp very helpful.
