### ISSUE TITLE
CMake Error at src/CMakeLists.txt:104 (rocm_set_soversion)

### ISSUE THREAD

**Issue by paolodalberto** [ROCmSoftwarePlatform/rocALUTION#116]
installed rocBLAS, rocSPARSE, rocRAND 
....

paolo@fastmmw:~/FastMM/Epyc/rocALUTION$ ./install.sh -idc
Creating project build directory in: ./build
[sudo] password for paolo: 
Hit:1 http://repo.radeon.com/rocm/apt/debian xenial InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease        
Hit:3 http://us.archive.ubuntu.com/ubuntu bionic InRelease               
Hit:4 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done                     
Building dependency tree       
Reading state information... Done
All packages are up to date.
~/FastMM/Epyc/rocALUTION ~/FastMM/Epyc/rocALUTION
Building googletest from source; installing into /usr/local
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_BOOST

-- Build files have been written to: /home/paolo/FastMM/Epyc/rocALUTION/build/deps
Scanning dependencies of target install
Built target install
~/FastMM/Epyc/rocALUTION
~/FastMM/Epyc/rocALUTION ~/FastMM/Epyc/rocALUTION
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Found HIP: /opt/rocm-3.8.0/hip (found version "3.8.20371-d1886b0b") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at src/CMakeLists.txt:104 (rocm_set_soversion):
  Unknown CMake command "rocm_set_soversion".

-- Configuring incomplete, errors occurred!
See also "/home/paolo/FastMM/Epyc/rocALUTION/build/release/CMakeFiles/CMakeOutput.log".
See also "/home/paolo/FastMM/Epyc/rocALUTION/build/release/CMakeFiles/CMakeError.log".

**Comment by paolodalberto** [comment]
Any help is welcome thank you

**Comment by paolodalberto** [comment]
one step forward:

 export ROCM_DIR=/opt/rocm/share/rocm/cmake/
 ./install.sh -icd

----
1 warning generated when compiling for host.
1 warning generated when compiling for gfx906.
1 warning generated when compiling for host.
In file included from /home/paolo/FastMM/Epyc/rocALUTION/src/base/hip/hip_matrix_csr.cpp:35:
In file included from /home/paolo/FastMM/Epyc/rocALUTION/src/base/hip/hip_vector.hpp:32:
In file included from /opt/rocm-3.8.0/include/hip/hip_runtime.h:53:
/opt/rocm-3.8.0/include/hip/hip_common.h:30:9: warning: '__HIP_PLATFORM_HCC__' macro redefined [-Wmacro-redefined]
#define __HIP_PLATFORM_HCC__
        ^
<command line>:7:9: note: previous definition is here
#define __HIP_PLATFORM_HCC__ 1
        ^
1 warning generated when compiling for gfx908.
In file included from /home/paolo/FastMM/Epyc/rocALUTION/src/base/hip/hip_matrix_csr.cpp:35:
In file included from /home/paolo/FastMM/Epyc/rocALUTION/src/base/hip/hip_vector.hpp:32:
In file included from /opt/rocm-3.8.0/include/hip/hip_runtime.h:53:
/opt/rocm-3.8.0/include/hip/hip_common.h:30:9: warning: '__HIP_PLATFORM_HCC__' macro redefined [-Wmacro-redefined]
#define __HIP_PLATFORM_HCC__
        ^
<command line>:7:9: note: previous definition is here
#define __HIP_PLATFORM_HCC__ 1
        ^
1 warning generated when compiling for host.
CMakeFiles/Makefile2:87: recipe for target 'src/CMakeFiles/rocalution_hip.dir/all' failed
make[1]: *** [src/CMakeFiles/rocalution_hip.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by paolodalberto** [comment]
one step forward

[  9%] Building HIPCC object src/CMakeFiles/rocalution_hip.dir/base/hip/rocalution_hip_generated_hip_matrix_bcsr.cpp.o
In file included from /home/paolo/FastMM/Epyc/rocALUTION/src/base/hip/hip_vector.cpp:45:
/home/paolo/FastMM/Epyc/rocALUTION/src/base/hip/hip_rand_normal.hpp:28:10: fatal error: 'rocrand/rocrand.hpp' file not found
#include <rocrand/rocrand.hpp>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated when compiling for host.
CMake Error at rocalution_hip_generated_hip_vector.cpp.o.cmake:138 (message):
  Error generating
  /home/paolo/FastMM/Epyc/rocALUTION/build/src/CMakeFiles/rocalution_hip.dir/base/hip/./rocalution_hip_generated_hip_vector.cpp.o

**Comment by paolodalberto** [comment]
rocRAND install only the C includes

Install the project...
-- Install configuration: "Release"
-- Installing: /opt/rocm/rocrand/lib/librocrand.so.1.1
-- Up-to-date: /opt/rocm/rocrand/lib/librocrand.so.1
-- Up-to-date: /opt/rocm/rocrand/lib/librocrand.so
-- Set runtime path of "/opt/rocm/rocrand/lib/librocrand.so.1.1" to "/opt/rocm/lib"
-- Up-to-date: /opt/rocm/rocrand/include
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_discrete.h
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_common.h
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_normal.h
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_xorwow_precomputed.h
-- Up-to-date: /opt/rocm/rocrand/include/rocrand.hpp
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_log_normal.h
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_discrete_types.h
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_sobol32.h
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_mrg32k3a_precomputed.h
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_mrg32k3a.h
-- Up-to-date: /opt/rocm/rocrand/include/rocrand.h
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_philox4x32_10.h
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_uniform.h
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_xorwow.h
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_mtgp32_11213.h
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_kernel.h
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_sobol_precomputed.h
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_poisson.h
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_mtgp32.h
-- Up-to-date: /opt/rocm/rocrand/include
-- Up-to-date: /opt/rocm/rocrand/include/rocrand_version.h
-- Up-to-date: /opt/rocm/rocrand/lib/cmake/rocrand/rocrand-targets.cmake
-- Installing: /opt/rocm/rocrand/lib/cmake/rocrand/rocrand-targets-release.cmake
-- Installing: /opt/rocm/rocrand/lib/cmake/rocrand/rocrand-config.cmake
-- Up-to-date: /opt/rocm/rocrand/lib/cmake/rocrand/rocrand-config-version.cmake
-- Installing: /opt/rocm/hiprand/lib/libhiprand.so.1.1
-- Up-to-date: /opt/rocm/hiprand/lib/libhiprand.so.1
-- Up-to-date: /opt/rocm/hiprand/lib/libhiprand.so
-- Set runtime path of "/opt/rocm/hiprand/lib/libhiprand.so.1.1" to "/opt/rocm/rocrand/lib:/opt/rocm/lib"
-- Up-to-date: /opt/rocm/hiprand/include
-- Up-to-date: /opt/rocm/hiprand/include/hiprand_mtgp32_host.h
-- Up-to-date: /opt/rocm/hiprand/include/hiprand_kernel_nvcc.h
-- Up-to-date: /opt/rocm/hiprand/include/hiprand_kernel.h
-- Up-to-date: /opt/rocm/hiprand/include/hiprand.hpp
-- Up-to-date: /opt/rocm/hiprand/include/hiprand_kernel_hcc.h
-- Up-to-date: /opt/rocm/hiprand/include/hiprand.h
-- Up-to-date: /opt/rocm/hiprand/include/hiprand_nvcc.h
-- Up-to-date: /opt/rocm/hiprand/include/hiprand_hcc.h
-- Up-to-date: /opt/rocm/hiprand/include
-- Up-to-date: /opt/rocm/hiprand/include/hiprand_version.h
-- Up-to-date: /opt/rocm/hiprand/lib/cmake/hiprand/hiprand-targets.cmake
-- Installing: /opt/rocm/hiprand/lib/cmake/hiprand/hiprand-targets-release.cmake
-- Installing: /opt/rocm/hiprand/lib/cmake/hiprand/hiprand-config.cmake
-- Up-to-date: /opt/rocm/hiprand/lib/cmake/hiprand/hiprand-config-version.cmake
-- Installing: /opt/rocm/rocrand/src/fortran/rocrand_m.f90
-- Installing: /opt/rocm/rocrand/src/fortran/hip_m.f90
-- Installing: /opt/rocm/hiprand/src/fortran/hiprand_m.f90
-- Installing: /opt/rocm/hiprand/src/fortran/hip_m.f90

**Comment by paolodalberto** [comment]
manually changed the 

#include "hip_rand.hpp"
#include <hip/hip_runtime.h>
#include <rocrand.hpp>

compilation successful 

however 
paolo@fastmmw:~/FastMM/Epyc/rocALUTION/build$ ./clients/staging/cg  ~/FastMM/Epyc/SparseFastMM/python/MTX/pdb1HYS.mtx /src/external/hip-on-vdi/rocclr/hip_code_object.cpp:92: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")
Aborted (core dumped)

**Comment by paolodalberto** [comment]
The goal is to run solver on GPUs

**Comment by xuhuisheng** [comment]
Which gpu are you used?
e.g. navi10 isnot supported offically. Please refer here https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1106

**Comment by paolodalberto** [comment]
ellesmere (ProDuo) I do not have a navi
I will play with Fiji and Vega 20

**Comment by paolodalberto** [comment]
rocSPARSE works

**Comment by paolodalberto** [comment]
it will be helpful to see what binarary are missing  ....

**Comment by paolodalberto** [comment]
let me build rocBLAS from scratch

**Comment by paolodalberto** [comment]
*******                  
Agent 2                  
*******                  
  Name:                    gfx803                             
  Uuid:                    GPU-XX                             
  Marketing Name:          Ellesmere [Radeon Pro WX 7100]     
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          4096(0x1000)                       
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
  Chip ID:                 26564(0x67c4)                      
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1243                               
  BDFID:                   17152                              
  Internal Node ID:        1                                  
  Compute Unit:            36                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16777216(0x1000000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx803          
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*******                  
Agent 3                  
*******                  
  Name:                    gfx803                             
  Uuid:                    GPU-XX                             
  Marketing Name:          Ellesmere [Radeon Pro WX 7100]     
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          4096(0x1000)                       
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    2                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
  Chip ID:                 26564(0x67c4)                      
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1243                               
  BDFID:                   17408                              
  Internal Node ID:        2                                  
  Compute Unit:            36                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16777216(0x1000000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx803          
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***             
paolo@fastmmw:~/FastMM/Epyc/rocALUTION/build$

**Comment by paolodalberto** [comment]
nope ... let see if something changes with a different GPU

**Comment by paolodalberto** [comment]
using a different GPU and re-building does not make any difference

**Comment by xuhuisheng** [comment]
Mostly rocBLAS report missing Tensile_Library_803.co, please refer here:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1106#issuecomment-688132238

**Comment by paolodalberto** [comment]
I can check but rocBLAS worked

**Comment by paolodalberto** [comment]
paolo@fastmmw:~/FastMM$ ls -lrt /opt/rocm-3.8.0/rocblas/lib/library/
total 435072
-rw-r--r-- 1 root root  13447896 Oct 10 15:02 Kernels.so-000-gfx908.hsaco
-rw-r--r-- 1 root root  13435608 Oct 10 15:02 Kernels.so-000-gfx906.hsaco
-rw-r--r-- 1 root root  15234136 Oct 10 15:02 Kernels.so-000-gfx900.hsaco
-rw-r--r-- 1 root root  14482368 Oct 10 15:02 Kernels.so-000-gfx803.hsaco
-rw-r--r-- 1 root root  13828720 Oct 10 15:02 Kernels.so-000-gfx1011.hsaco
-rw-r--r-- 1 root root  14992568 Oct 10 15:02 Kernels.so-000-gfx1010.hsaco
-rw-r--r-- 1 root root 127802736 Oct 10 15:02 TensileLibrary_gfx908.co
-rw-r--r-- 1 root root   3658000 Oct 10 15:02 TensileLibrary_gfx803.co
-rw-r--r-- 1 root root  35691768 Oct 10 15:02 TensileLibrary_gfx900.co
-rw-r--r-- 1 root root 102552952 Oct 10 15:02 TensileLibrary_gfx906.co
-rw-r--r-- 1 root root  90358993 Oct 10 15:02 TensileLibrary.dat

Tensile is there alright 
let's if it is related to rocrand (which is flimsy)

**Comment by paolodalberto** [comment]
Total Test time (real) =   8.99 sec

The following tests FAILED:
	  3 - test_poisson_distribution (Not Run)
	  4 - test_rocrand_basic (Not Run)
	  5 - test_rocrand_cpp_wrapper (Not Run)
	  6 - test_rocrand_generate (Not Run)
	  7 - test_rocrand_generate_log_normal (Not Run)
	  8 - test_rocrand_generate_normal (Not Run)
	  9 - test_rocrand_generate_poisson (Not Run)
	 10 - test_rocrand_generate_uniform (Not Run)
	 12 - test_rocrand_kernel_mrg32k3a (Not Run)
	 13 - test_rocrand_kernel_mtgp32 (Not Run)
	 14 - test_rocrand_kernel_philox4x32_10 (Not Run)
	 15 - test_rocrand_kernel_sobol32 (Not Run)
	 16 - test_rocrand_kernel_xorwow (Not Run)
	 24 - test_hiprand_cpp_wrapper (Not Run)
	 25 - test_hiprand_kernel (Not Run)
	 26 - test_rocrand_fortran_wrapper (Not Run)
	 27 - test_hiprand_fortran_wrapper (Not Run)
Errors while running CTest

**Comment by paolodalberto** [comment]
```
./rocsparse-bench  
Query device success: there are 2 devices
Device ID 0: Ellesmere [Radeon Pro WX 7100]
-------------------------------------------------------------------------
with 16384MB memory, clock rate 1243MHz @ computing capability 8.3
maxGridDimX 2147483647, sharedMemPerBlock 64KB, maxThreadsPerBlock 1024
wavefrontSize 64
-------------------------------------------------------------------------
Device ID 1: Ellesmere [Radeon Pro WX 7100]
-------------------------------------------------------------------------
with 16384MB memory, clock rate 1243MHz @ computing capability 8.3
maxGridDimX 2147483647, sharedMemPerBlock 64KB, maxThreadsPerBlock 1024
wavefrontSize 64
-------------------------------------------------------------------------
Using device ID 0 (Ellesmere [Radeon Pro WX 7100]) for rocSPARSE
-------------------------------------------------------------------------
rocSPARSE version: 1.17.8-855-0192c4b
M           nnz         alpha           GFlop/s     GB/s        usec        iter        verified    
128         32          1.00            0.01        0.06        8.10        10          no         
```

**Comment by paolodalberto** [comment]
How do you check what binary needs?
```
 ./clients/staging/cg ~/FastMM/Epyc/SparseFastMM/python/MTX/young4c.mtx 4
/src/external/hip-on-vdi/rocclr/hip_code_object.cpp:92: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")
```

**Comment by paolodalberto** [comment]
ViennaCL is the only one I could execute a cg so far ... should I implement cg using rocBLAS and rocSPARSE directly

**Comment by paolodalberto** [comment]
paolo@fastmmw:~/FastMM/Epyc/ViennaCL-1.7.1/build$ ./examples/tutorial/iterative-custom /home/paolo/FastMM/Epyc/SparseFastMM/python/MTX/Lin.mtx
gfx803
0x562f6477c810
/home/paolo/FastMM/Epyc/SparseFastMM/python/MTX/Lin.mtx
----- CG Method -----
Time difference = 816916[µs]
	iterations:100 Error:0.108561
----- BiCGStab Method -----
Time difference = 435005[µs]
	iterations: 100 Error:7.60943e-05
----- GMRES Method -----
Time difference = 46114[µs]
	iterations: 100 Error:0.0655528
!!!! TUTORIAL COMPLETED SUCCESSFULLY !!!!

**Comment by paolodalberto** [comment]
No comments 
No further help ?

**Comment by paolodalberto** [comment]
resolved 
AMDGPU_TARGETS=gfx803;gfx900;gfx906;gfx908

Adding gfx803 for vega 20 I will check

**Comment by paolodalberto** [comment]
```
paolo@fastmmw:~/FastMM/Epyc/rocALUTION/build$ ./clients/staging/cg gr_30_30.mtx 1
OMP: Info #270: omp_get_nested routine deprecated, please use omp_get_max_active_levels instead.
OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Number of CPU cores: 32
Host thread affinity policy - thread mapping on every core
Number of HIP devices in the system: 3
HURRA 
rocALUTION ver 1.11.0-539-9e5603a
rocALUTION platform is initialized
Accelerator backend: HIP
OpenMP threads: 32
rocBLAS ver 2.33.0.2836-fbe56c5e
rocSPARSE ver 1.17.8-855-0192c4b
Selected HIP device: 1
------------------------------------------------
Device number: 0
Device name: Vega 20
totalGlobalMem: 16368 MByte
clockRate: 1801000
compute capability: 9.6
------------------------------------------------
------------------------------------------------
Device number: 1
Device name: Ellesmere [Radeon Pro WX 7100]
totalGlobalMem: 16384 MByte
clockRate: 1243000
compute capability: 8.3
------------------------------------------------
------------------------------------------------
Device number: 2
Device name: Ellesmere [Radeon Pro WX 7100]
totalGlobalMem: 16384 MByte
clockRate: 1243000
compute capability: 8.3
------------------------------------------------
MPI is not initialized
ReadFileMTX: filename=gr_30_30.mtx; reading...
ReadFileMTX: filename=gr_30_30.mtx; done
LocalMatrix name=gr_30_30.mtx; rows=900; cols=900; nnz=7744; prec=64bit; format=CSR; host backend={CPU(OpenMP)}; accelerator backend={HIP}; current=HIP
PCG solver starts, with preconditioner:
Jacobi preconditioner
IterationControl criteria: abs tol=1e-15; rel tol=1e-06; div tol=1e+08; max iter=1000000
IterationControl initial residual = 33.2866
IterationControl RELATIVE criteria has been reached: res norm=2.03206e-05; rel val=6.10474e-07; iter=36
PCG ends
Solver execution:0.034622 sec
||e - x||_2 = 8.01194e-06
OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

```
