### ISSUE TITLE
hip_add_library

### ISSUE THREAD

**Issue by paolodalberto** [ROCmSoftwarePlatform/rocALUTION#120]
```
rocm-user@5398fc181728:~/rocALUTION/build$ cmake --debug-find ../ -DSUPPORT_HIP=ON -DSUPPORT_OMP=ON -DBUILD_EXAMPLES=ON 
-- Setting build type to 'Release' as none was specified.
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS) 
-- Could NOT find MPI (missing: MPI_CXX_FOUND) 
-- MPI not found. Compiling WITHOUT MPI support.
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- ROCclr at /opt/rocm/lib/cmake/rocclr
-- hip::amdhip64 is SHARED_LIBRARY
-- hip::amdhip64 is SHARED_LIBRARY
CMake Error at src/CMakeLists.txt:129 (hip_add_library):
  Unknown CMake command "hip_add_library".


-- Configuring incomplete, errors occurred!
See also "/home/rocm-user/rocALUTION/build/CMakeFiles/CMakeOutput.log".
See also "/home/rocm-user/rocALUTION/build/CMakeFiles/CMakeError.log".
rocm-user@5398fc181728:~/rocALUTION/build$ sudo apt install amdhip64 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
```
E: Unable to locate package amdhip64

**Comment by paolodalberto** [comment]
rocm-user@5398fc181728:~/rocALUTION/build$ ls /opt/rocm/ -lrt 
total 84
drwxr-xr-x  3 root root 4096 Jun 11 15:44 rocclr
drwxr-xr-x  8 root root 4096 Jun 11 15:44 hip
drwxr-xr-x  3 root root 4096 Jun 11 15:44 hsa-amd-aqlprofile
drwxr-xr-x  3 root root 4096 Jun 11 15:44 amdgcn
drwxr-xr-x  5 root root 4096 Jun 11 15:44 opencl
drwxr-xr-x  7 root root 4096 Jun 11 15:44 llvm
drwxr-xr-x 10 root root 4096 Jun 11 15:44 share
drwxr-xr-x  5 root root 4096 Jun 11 15:44 roctracer
drwxr-xr-x  6 root root 4096 Jun 11 15:44 rocprofiler
drwxr-xr-x  6 root root 4096 Jun 11 15:44 rocm_smi
drwxr-xr-x  4 root root 4096 Jun 11 15:44 oam
drwxr-xr-x  4 root root 4096 Jun 11 15:44 hsa
drwxr-xr-x  2 root root 4096 Jun 11 15:44 bin
drwxr-xr-x  4 root root 4096 Jul  5 17:40 rocprim
drwxr-xr-x  4 root root 4096 Jul  5 18:28 rocblas
drwxr-xr-x  4 root root 4096 Jul  5 18:51 hiprand
drwxr-xr-x  4 root root 4096 Jul  5 18:51 rocrand
drwxr-xr-x  4 root root 4096 Jul  5 18:51 rocsparse
drwxr-xr-x  1 root root 4096 Jul  5 18:53 lib
drwxr-xr-x  1 root root 4096 Jul  5 18:53 include

**Comment by paolodalberto** [comment]
this is a docker image 
```
$ docker pull rocm/rocm-terminal
$ docker run -it --rm --device=/dev/kfd --device=/dev/dri --group-add video rocm/rocm-terminal
```

**Comment by ntrost57** [comment]
`cmake --debug-find ../ -DSUPPORT_HIP=ON -DSUPPORT_OMP=ON -DBUILD_EXAMPLES=ON -DROCM_PATH=/path/to/rocm/`

**Comment by paolodalberto** [comment]
works
