### ISSUE TITLE
HostMatrixCSR: ILU factorization requires sorting columns first

### ISSUE THREAD

**Issue by j4yan** [ROCmSoftwarePlatform/rocALUTION#121]
Both `ILU0Factorize` and `ILUTFactorize` assume that the columns are sorted, but there's no guarantee `Sort` is already called.

**Comment by ntrost57** [comment]
That's correct, column array need to be sorted within each row. It's the users responsibility to ensure this. We will update the user manual accordingly, thanks!

**Comment by j4yan** [comment]
How about adding a flag, `sorted`, to the class? Then `Sort` can be called whenever needed.

**Comment by ntrost57** [comment]
That's something, we might consider in a future release, thanks.

**Comment by ntrost57** [comment]
The user manual now states, that CSR columns have to be sorted within each row and COO matrices need to be sorted by row.
