### ISSUE TITLE
overlap in Additive Schwarz

### ISSUE THREAD

**Issue by j4yan** [ROCmSoftwarePlatform/rocALUTION#122]
Currently the extended matrix of a subblock includes `overlap` rows above the subblock and `overlap` rows below the subblock. An alternative (which is also typical) approach is to include neighboring rows and columns that correspond to the ghost/boarder indices (in the corresponding graph). If in the future the distributed version of additive Schwarz is implemented, the suggested approach will share the same communication pattern as the SpMV.

**Comment by doctorcolinsmith** [comment]
@j4yan Thank you for the suggestion.

@ntrost57 Can you please review?

**Comment by doctorcolinsmith** [comment]
Thanks again @j4yan for the suggestion!

We will review this design recommendation internally.  Closing the issue as there is no other immediate action to take.
