### ISSUE TITLE
Integration and usage documentation with OpenFoam as ROCm alternative to PARALUTION

### ISSUE THREAD

**Issue by FCLC** [ROCmSoftwarePlatform/rocALUTION#123]
As of now I'm unable to integrate rocALUTION, rocSPARSE, and other required ROCm 4.3 libraries into any version of Open Foam, be it V2012, 2106, V9.3 etc. 

No specific documentation is provided on the ROCm side for integration into OpenFoam. I've RTFM'ed 
1. OpenFOAM manual for adding external libs: https://cfd.direct/openfoam/user-guide/v9-compiling-applications/
2. Paralution guide for integrating into OpenFOAM: https://usermanual.wiki/Document/paralutionusermanual.1846194347/html#pf50

Any guidance on integration would be greatly appreciated.

**Comment by ntrost57** [comment]
Currently, we do not support OpenFOAM.

**Comment by FCLC** [comment]
> Currently, we do not support OpenFOAM.

Ah, unfortunate. Any possibility to mark this as a feature request? Would prefer to stay with an open compute stack over Cuda. 

Was also under the impression that it was on the road map per https://github.com/Atizar/RapidCFD-dev/issues/46#issuecomment-425268846 

With that being the case, any suggestions for using GPU acceleration with my Navi GPU with OpenFoam?

**Comment by ntrost57** [comment]
Closing this, as we currently have no plans to add OpenFOAM support to rocALUTION. I cannot comment on RapidCFD.
You could, however, try to port the existing PARALUTION plugin to rocALUTION in order to import/export OpenFOAM objects.

**Comment by littlewu2508** [comment]
@ntrost57 I guess maybe you can start from the `src/examples/OpenFOAM/Laplace` of paralution, replace `#include <paralution.hpp>` to `#include <rocalution.hpp>`, and `paralution::` to `rocalution::`

However, in folder `system`, I'm not sure if `paralution` string in the file and filename should be replaced.

Then modify the FLAGS in `Make/options`, to include rocalution header path and link the rocALUTION shared libs.
