### ISSUE TITLE
Global 

### ISSUE THREAD

**Issue by pledac** [ROCmSoftwarePlatform/rocALUTION#147]
Hello,

I have a question about global matrix/vector. Is it possible to use these objects even in sequential mode (1 MPI rank) ? All the samples warn about 2 MPI processes. I would like to avoid using local matrix for sequential computation and global matrix for parallel computation... I see no tips in the documentation to use global matrix/vector with less than 2 MPI ranks.

Thanks !

**Comment by ntrost57** [comment]
The examples will require 2 MPI ranks in order to work, but in theory, global structures should also work with a single MPI rank. Did you encounter any issues?

**Comment by pledac** [comment]
Yes, using cg_mpi sample (after commenting >=2 MPI rank test), I get:

**./clients/staging/cg_mpi ../GPU4_sbaij.mtx 
No OpenMP support
rocALUTION ver 1.13.2-11bdec6-dirty
rocALUTION platform is initialized
Accelerator backend: None
No OpenMP support
MPI rank:0
MPI size:1
ReadFileMTX: filename=../GPU4_sbaij.mtx; reading...
ReadFileMTX: filename=../GPU4_sbaij.mtx; done
Fatal error in PMPI_Waitall: Invalid count, error stack:
PMPI_Waitall(392): MPI_Waitall(count=-1, req_array=(nil), status_array=0x1) failed
PMPI_Waitall(359): Negative count, value is -1
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=269107714
:
system msg for write_line failure : Bad file descriptor**

I guess the code into common.hpp to distribute matrix should be changed for 1 MPI rank. Good to know global matrix/vector should work with a single rank. I am going to try to change the sample and will report any issue. Thanks !

**Comment by ntrost57** [comment]
The example will not work for single MPI rank, that's expected. But you should be able to fully bypass the distribution.

**Comment by pledac** [comment]
Hmmm. Not sure **GlobalVector** may run on single rank.

Got an assert size>0 in:
    
```
void LocalVector<ValueType>::SetIndexArray(int size, const int* index)
    {
        log_debug(this, "LocalVector::SetIndexArray()", size, index);
        assert(size > 0);
        assert(index != NULL);
        this->vector_->SetIndexArray(size, index);

```
When SetIndexArray was called from an Allocate on a GlobalVector:

 ```
 template <typename ValueType>
    void GlobalVector<ValueType>::Allocate(std::string name, IndexType2 size)
    {
        log_debug(this, "GlobalVector::Allocate()", name, size);
        assert(this->pm_ != NULL);
        assert(this->pm_->global_size_ == size);
        assert(size <= std::numeric_limits<IndexType2>::max());
        ...

        this->object_name_ = name;
        this->vector_interior_.Allocate(interior_name, this->pm_->GetLocalSize());
        this->vector_ghost_.Allocate(ghost_name, this->pm_->GetNumReceivers());
        this->vector_interior_.SetIndexArray(this->pm_->GetNumSenders(),
                                             this->pm_->boundary_index_);
```

Indeed, I didn't define in the cg_mpi.cpp sample, the Senders and Receivers for a single rank case as there are no neighbours...

**Comment by ntrost57** [comment]
There are few places that do not allow nullptrs when no communication pattern is required. I'll update those places to make it work.

**Comment by ntrost57** [comment]
I have updated develop branch with the changes. The examples should also work with single MPI now. Let me know if it works for you.

**Comment by pledac** [comment]
A very quick test seems indicate it works now. Thanks a lot ! It will be really useful for us:

portable: /tmp/rocALUTION (develop) > ./build/clients/staging/cg_mpi VDF.mtx
No OpenMP support
rocALUTION ver 2.1.2-ce712e0
rocALUTION platform is initialized
Accelerator backend: None
No OpenMP support
MPI rank:0
MPI size:1
ReadFileMTX: filename=VDF.mtx; reading...
ReadFileMTX: filename=VDF.mtx; done
GlobalMatrix name=mat; rows=9; cols=9; nnz=33; prec=64bit; format=CSR/CSR; subdomains=1; host backend={CPU}; accelerator backend={None}; current=CPU
PCG solver starts, with preconditioner:
Jacobi preconditioner
IterationControl criteria: abs tol=1e-15; rel tol=1e-06; div tol=1e+08; max iter=1000000
IterationControl initial residual = 0
IterationControl ABSOLUTE criteria has been reached: res norm=0; rel val=-nan; iter=0
PCG ends
Solving: 7.3e-05 sec
||e - x||_2 = 3

**Comment by ntrost57** [comment]
Feel free to re-open, when you're facing additional problems running single MPI process.
