### ISSUE TITLE
ifdef SUPPORT_MULTINODE

### ISSUE THREAD

**Issue by pledac** [ROCmSoftwarePlatform/rocALUTION#153]
Hello,

Just point out for your interest a typo in line 117 of this [file](https://github.com/ROCmSoftwarePlatform/rocALUTION/blob/develop/src/base/backend_manager.cpp).

**#ifdef SUPPORT_MULITNODE**
Instead of:
**#ifdef SUPPORT_MULTINODE**

**Comment by ntrost57** [comment]
Good catch, thanks.

**Comment by doctorcolinsmith** [comment]
This is fixed in the code and will be in an upcoming release.
