### ISSUE TITLE
rocALUTION for fortran

### ISSUE THREAD

**Issue by pelyakim** [ROCmSoftwarePlatform/rocALUTION#163]
Hello, I would like to use rocALUTION for a CFD code to use it on the new machine of CINES (France) Adastra (AMD processors and graphics cards). I would like to solve a pseudo 3D fish equation with the CG solver and an algebraic multi grid preconditioner (SA-AMG). Would you have a fortran interface to use rocALUTION ? Thanks for your answer.

**Comment by pelyakim** [comment]
Thank you for your answer. Do you think you can help me to interface my problem in Fortran?

**Comment by pelyakim** [comment]
I am currently using the cg-amg.cpp example that I am trying to interface to fortran.

**Comment by ntrost57** [comment]
There is currently no official support.
However, you could take a look at the [PARALUTION library](www.paralution.com) rocALUTION is based on. It contains a FORTRAN plugin and you should be able to convert it for your usage. Check out the tarball and files in `src/examples/fortran/` as well as `plug-ins/paralution_fortran.cpp'.

**Comment by pelyakim** [comment]
Thank you for this information. I'm already on it actually! I've got it right on target.

**Comment by pelyakim** [comment]
In the code on which I work, we solve a linear system representing a 3D Poisson pseudo equation at each time iteration. 
In the fortran code, I have the matrix of this system in CSR format represented by the arrays row_offset, col and val which does not change for the single phase simulation. When I try to use rocALUTION I use the SetDataPtrCSR function to build the matrix that is used in the solver. However, I can't keep this matrix for the next iteration and the values I put in argument (row_offset, col and val) are deallocated I have the impression.  What do you advise me to do? Is SetDataPtrCSR the right function to do what I want ? Thank you for your answers and your help. Pierre

**Comment by ntrost57** [comment]
`SetDataPtrCSR()` will invalidate the original pointers. The data is not lost, but put inside the rocALUTION object. If you need raw pointer access again, you can use `LeaveDataPtrCSR()`. Be aware, that calling this functionality will return the data pointers on what ever backend the rocALUTION object was current located at. If you need your pointers on host, you might have to call `MoveToHost()` prior to `LeaveDataPtrCSR()`. Also, please note that calling `LeaveDataPtrCSR()` will invalidate/clear the rocALUTION object. Once you have modified your data, you can however put it back to rocALUTION (`SetDataPtrCSR()`). That way, you will avoid copying data and just set/get raw pointers.
Does this answer your question?

**Comment by pelyakim** [comment]
Thanks for your reply, I used intermediate arrays and the SetDataPtrCSR function with them for building the system matrix. Now I have another problem with the code for use with MPI, we compiled rocALUTION with the option -DSUPPORT_MPI=ON but when running a test case we have in the output logs the function info_rocalution(); returns "Multinode support disabled". In the code, moreover I give the communicator mpi_com_world of MPI_init(). Where do you think the problem comes from? Thanks for your answer. Sincerely, Pierre

**Comment by ntrost57** [comment]
Are you linking to the correct lib.so file? "Multinode support disabled" tells me you are running with an MPI disabled library.

**Comment by pelyakim** [comment]
Normally yes, I checked with ldd myexe and we link well on rocALUTION compiled with the option -DSUPPORT_MPI=ON, is it enough to have MPI support or should we do something else? Moreover, I have an error as soon as I get to the declaration of a GlobalMatrix type.

**Comment by ntrost57** [comment]
This all tells me, something goes wrong with the linking. Can you make sure, there is no other copy of rocalution installed on the system (e.g. in /opt/rocm/)?

**Comment by pelyakim** [comment]
Thanks a lot for your advice, there was indeed another rocalution in /opt/rocm2.3. I fixed the problem by filling the LD_LIBRARY_PATH. Thanks again.
