### ISSUE TITLE
Directly update (set/add) LocalMatrix accelerator values

### ISSUE THREAD

**Issue by jappa** [ROCmSoftwarePlatform/rocALUTION#167]
Is it possible to update the values of a LocalMatrix/LocalVector from a kernel running on the accelerator?

**Comment by ntrost57** [comment]
Hi Jappa,
You can use the `LocalVector::LeaveDataPtr()` functionality, to get raw pointer access and `LocalVector::SetDataPtr()` to pass it back to rocALUTION. There is similar functionality also for LocalMatrix class. Is this what you are looking for?

**Comment by ntrost57** [comment]
Yes, pointers will be located, where ever the object was currently located on. Also note, that SetDataPtr requires the pointers to be located on the same backend as the rocalution object (which in your example should be fine).
When calling LeaveDataPtr, the rocalution object will not be valid anymore until pointers are set back using SetDataPtr. Similarly, mat_row_offset, mat_col and mat_val will be invalid (null) after calling SetDataPtrCSR.

**Comment by jappa** [comment]
Thanks and yes I will need to update both interior and ghost matrices.  
It would be useful if GlobalMatrix had non const versions of GetInterior() and GetGhost() for this type of functionality as I am always a bit wary of having to use const_cast

**Comment by ntrost57** [comment]
You could directly extract the pointers using `GlobalMatrix::LeaveDataPtr` to avoid the cast.

**Comment by jappa** [comment]
Ah yes I had not noticed the Ghost versions of those functions. Thanks
