### ISSUE TITLE
readthedocs.io documentation missing

### ISSUE THREAD

**Issue by ckastner** [ROCmSoftwarePlatform/rocALUTION#194]
Hi,

[README.md](https://github.com/ROCmSoftwarePlatform/rocALUTION/blob/develop/README.md?plain=1#L108) points to [https://rocalution.readthedocs.io](https://rocalution.readthedocs.io) for the current documentation, but it seems that the documentation has not been pushed there. Opening the link results in a 404.

**Comment by doctorcolinsmith** [comment]
Hello @ckastner.  The documentation has moved to https://rocm.docs.amd.com/projects/rocALUTION/en/latest/index.html.  We'll get the readme updated.

**Comment by jsandham** [comment]
This is now fixed.

**Comment by jsandham** [comment]
Actually fixed in develop. The fix should be contained in the rocm-6.0 release.
