### ISSUE TITLE
[Issue]: `rocalution-config.cmake` file attempts to find HIP even if rocALUTION was built w/o HIP support

### ISSUE THREAD

**Issue by juhanikataja** [ROCmSoftwarePlatform/rocALUTION#247]
### Problem Description

rocALUTION compiles without HIP support but resulting `lib/cmake/rocalution/rocalution-config.cmake` anyhow tries to find HIP (line 90: `find_dependency(HIP)`).

Commenting that line out will enables use of rocALUTION even without HIP being available.

No ROCm/HIP was needed to build rocALUTION.

### Operating System

22.04.5 LTS (Jammy Jellyfish)

### CPU

 AMD Ryzen 5 7530U with Radeon Graphics

### GPU

AMD Instinct MI250X

### ROCm Version

ROCm 6.2.0

### ROCm Component

HIP

**Comment by mmuetzel** [comment]
See #248 for a potential fix.

**Comment by mmuetzel** [comment]
Are you in contact with the people that package rocALUTION for Debian?
If you are: Could you please ask if they could cherry-pick the commit that fixes this issue (https://github.com/ROCm/rocALUTION/commit/a7cdd397f1a293fe8fab2082e6e6aa13ac4af640)?
As it stands, the rocalution package that is distributed by Ubuntu (inherited from Debian afaict) cannot be used in CMake projects without work-arounds.

**Comment by darren-amd** [comment]
Hi @juhanikataja,

This issue should be resolved with #248, please give it a try and let me know if the issue persists, thanks!

**Comment by juhanikataja** [comment]
Thanks @darren-amd and @mmuetzel!

The issue did resolve in commit a7cdd397f1a293fe8fab2082e6e6aa13ac4af640

I don't know the rocALUTION Debian packagers unfortunately.

**Comment by darren-amd** [comment]
Awesome! Closing as complete.
